add riscv64 cross build

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -206,3 +206,66 @@ jobs:
           compression-level: 0
           path: ${{ env.ARCHIVE }}/**
 
+  build-cross:
+    runs-on: ubuntu-latest
+
+    strategy:
+      matrix:
+        os: [
+            { name: linux-riscv64-gnu, target: riscv64gc-unknown-linux-gnu },
+        ]
+
+    defaults:
+      run:
+        shell: bash
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
+          ref: ${{ inputs.commit }}
+
+      - name: Install Rust
+        uses: dtolnay/rust-toolchain@master
+        with:
+          toolchain: stable
+
+      - name: Install cross toolchain
+        uses: taiki-e/setup-cross-toolchain-action@v1
+        with:
+          target: ${{ matrix.os.target }}
+
+      - name: Build
+        run: cargo build --release --package cuprated
+
+      - name: Generate config
+        run: cargo run --release --package cuprated -- --generate-config > Cuprated.toml
+
+      - name: Generate Archive
+        run: |
+          set -e -o pipefail # Exit on failures
+          umask 0077         # 700 permissions
+          export TZ=UTC      # UTC timezone
+
+          # Reset archive directory in-case.
+          rm -rf ${{ env.ARCHIVE }}
+          mkdir -p ${{ env.ARCHIVE }}
+
+          readonly ARCHIVE=$(realpath ${{ env.ARCHIVE }})
+          readonly VERSION=$(grep '^version = ' binaries/cuprated/Cargo.toml | cut -d'"' -f2)
+          readonly OUT="target/$CARGO_BUILD_TARGET/release"
+          readonly ASSET="cuprated-$VERSION-$CARGO_BUILD_TARGET.tar.gz"
+
+          # Generate archives for Linux.
+          cp LICENSE-AGPL "$OUT/LICENSE"
+          cp binaries/cuprated/cuprated.service "$OUT"
+          mv Cuprated.toml "$OUT"
+          tar -czpf "$ARCHIVE/$ASSET" -C "$OUT" cuprated LICENSE Cuprated.toml cuprated.service
+
+      - name: Archive
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ matrix.os.name }}
+          compression-level: 0
+          path: ${{ env.ARCHIVE }}/**
